### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/hash-brown-router#15]
It would be nice to have some sort of example usage. Some API functions have no examples.

Perhaps one of the following options?

- example section in the readme, with a bunch of code
- example.js file (linked to in the readme)
- a link to it's usage inside the noddity webapp, or similar
- a demo on gh-pages, (similar to [simplest-asr-usage](http://tehshrike.github.io/simplest-abstract-state-router-usage/))
- add a code block to each API method

**Comment by TehShrike** [comment]
yeah, I think an example section would be good.
