### ISSUE TITLE
Sort by specificity

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/hash-brown-router#9]
Right now you can sort by the order the routes were added, or the reverse order. It would be nice to have an option to sort by specificity.

I want it to match based on how closely the URL matches the route. An exact string will win over a few params.

So if you have these routes...
```
/starred
/:user
/new/import
/new
/:user/:repo
```
...you're sent to `/new` or `/starred` if you browse to them. You'd never get sent to `/:user`, because it is less specific.

----

To implement, you'd first have to decide what it means to be more, or less specific. I'd say the number `:` characters tell you what you need.

```js
var routes = [
    '/starred',
    '/:user',
    '/new/import',
    '/new',
    '/:user/:repo'
]

routes.sort(function (route1, route2) {
    var count1 = (route1.match(/:/g) || []).length
    var count2 = (route2.match(/:/g) || []).length
    return count1 - count2
})
```
[jsfiddle](https://jsfiddle.net/6dex0472/1/)

**Comment by TehShrike** [comment]
I don't think this is possible - you can make some really complex routing strings.

Which is more specific, `/:foo+` or `/:foo(\\d+)`?

`/:foo/*` or `/:foo(\\d+)/*/:bar`?

My brain tells me that `/:foo` is less specific than `/:foo(\\d+)`, but how to detect that programmatically without a bunch of code or rules?

Having so many options for route matching means that you have to be very careful about how you're affecting your namespace when you add new routes to your app.

**Comment by TehShrike** [comment]
On regex specificity: http://stackoverflow.com/a/6698260/201789

**Comment by ArtskydJ** [comment]
Didn't realize this supported regexes in routes. I would personally be happy with a sort by number of params, because I do simple routes where there are few matches.

------

Any thoughts on supporting a sort function?

```js
var makeRouter = require('hash-brown-router')

var router = makeRouter({
    sort: function (a, b) { /* ... */ }
})
```

**Comment by TehShrike** [comment]
I'd feel pretty awkward about it, because I don't think it's easy to sort them programmatically, even if you limit yourself to a subset of possible parameter filters.

Which is more specific, `/butt/:foo/:bar/lol` or `/:foo/butt/:bar`?

**Comment by TehShrike** [comment]
Deriving meaning from the order that routes are added feels dirty in a stateful kind of way, but it is at least a way for the library consumer to indicate some meaning about which routes are more important than other without having to try to derive meaning from the route expressions themselves.

**Comment by ArtskydJ** [comment]
If someone creates the states `/foo/:wut` and `/:lol/bar`, and goes to `/foo/bar`, I don't know which state they should be directed to. I don't really think there's a right answer.

If I ever run across a module that sorts routes really well, I might investigate further. At this point, I'll just put my states in the right order. :smile:

**Comment by TehShrike** [comment]
Relevant: https://github.com/Matt-Esch/http-hash
